### ISSUE TITLE
Show items that only match selected tags

### ISSUE THREAD

**Issue by ln-dev7** [ln-dev7/cameroon-portfolios#15]
![Capture d’écran du 2022-06-26 04-09-17](https://user-images.githubusercontent.com/62269693/175797739-6ba35e25-4d17-4e19-ba0c-302be8ab20bc.png)

Normally this should return "No portfolios found..."
Because no one has the "Devops" and "Mobile" tags

@Sanix-Darker @Zaker237 good idea ?

**Comment by Sanix-Darker** [comment]
Mhhh... i was thinking it was an inclusive tag filtering...
like if one of the portofolio has "devOps" or "Mobile" it should be shown... 🤔

**Comment by ln-dev7** [comment]
in fact I myself do not know I wanted to know if it was a good trick or not ....

**Comment by Zaker237** [comment]
I think it will be better to have exact matching meaning that when more than one Tags are selected we show the Portfolios that include all the selected tags

**Comment by ln-dev7** [comment]
exactly
