### ISSUE TITLE
implement filter on tags

### ISSUE THREAD

**Issue by Zaker237** [ln-dev7/cameroon-portfolios#4]

**Comment by Zaker237** [comment]
non non @tchassijordan  tu peux te lancer dessus

**Comment by tchassijordan** [comment]
Okay, je le prend

**Comment by ln-dev7** [comment]
🔥🔥🔥

**Comment by armandwadji** [comment]
Bonjour, je trouve que vous avez une bonne idée…
Cependant dans le but de garder la main sur la BDD, je pense que ce serais mieux de générer une interface avec un formulaire à remplir avoir les vérifications nécessaires…
Ce serait plus sécurisé vous trouvez pas??

**Comment by ln-dev7** [comment]
Bonjour, tu parles d'un formulaire pour pouvoir add son portfolio ?

**Comment by tchassijordan** [comment]
Je pense qu'il veut dire. Créer une interface graphique pour l'ajout des portfolios et pas avec du code.

**Comment by ln-dev7** [comment]
Ahh si c'est ca, j'ai bien pensé mais la ca offre la possibilité a tout le monde d'ajouter son portfolio ( on ne pourra pas verifier si son lien est valide par exemple ... )

**Comment by Zaker237** [comment]
@ln-dev7 cest possible de vérifier qu'un lien est valide

Il suffit de faire un get request dessus et de s'assurer qu'on reçoit 200 comme status code

**Comment by tchassijordan** [comment]
@Zaker237 Intéressant t'a solution.  
Un autre problème qui peut s'élever et de vérifier que le lien entre est vraiment un portfolio et non un site quelconque.

**Comment by ln-dev7** [comment]
Voila exactement et il y'a aussi au niveau des tags une personne peut juste mettre "dsdsajdnasd" comme tag ...
Donc je pense que ajouter dans le code est une meilleure solution

**Comment by armandwadji** [comment]
Re bonjour 
Oui pour le lien du portfolio avec une réponse 200 à la requête de lien on vérifie si il est valide ou pas...
Cependant oui on ne pourras pas vérifier que ce lien dirige bien vers un portfolio.
Cela dit c'est un peu ça le but, 
Sur LinkedIn sur le lien portfolio tu peux maitre n'importe quel lien, cela te regarde pour la suite avec les futur recruteurs ou potentiels clients

**Comment by ln-dev7** [comment]
Donc meme si la personne met le lien vers netflix ou meme vers un site x pour toi ca derange pas ?

**Comment by armandwadji** [comment]
Si c'est très problématique 
Faudrait voir comment certains sites font pour faire ce genre de vérifications
Il y'a forcément une solution

**Comment by ln-dev7** [comment]
Sur LinkedIn les users veulent du travail normal qu'il doivent mettre un bon lien mais ici un user peut venir juste pour le "mauvais coeur" comme on dit souvent

**Comment by ln-dev7** [comment]
> Si c'est très problématique Faudrait voir comment certains sites font pour faire ce genre de vérifications Il y'a forcément une solution

J' ai deja visite trois repo qui stock les portfolio et c'est la meme approche 

https://github.com/wesbos/awesome-uses
https://github.com/emmabostian/developer-portfolios
https://github.com/ln-dev7/portfolio-ideas

**Comment by Sanix-Darker** [comment]
oups... just noticed that this issue was already taken ? 
https://github.com/ln-dev7/cameroon-portfolios/pull/12

**Comment by ln-dev7** [comment]
> oups... just noticed that this issue was already taken ? #12

Ah pas grave :)
Merciiii a toi
