### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by gabin-dongmo** [ln-dev7/cameroon-portfolios#8]
Hi guys,

Kind of putting the cart before the horse here. But I thought it would be interesting to make the project statically typed by adding TypeScript support. I think it's a good practice, as it helps improve the code quality and the developer experience.

I've already submitted a PR on that.

Do you guys think it's a good idea?

**Comment by Carter2307** [comment]
It's a great idea but in think The project is very basic.  it's open for everyone (beginner to advance). typescript add some logic That complicate thing

**Comment by gabin-dongmo** [comment]
@Carter2307 Can you please elaborate how TypeScript would make the basic project more complex?

**Comment by ln-dev7** [comment]
> @Carter2307 Can you please elaborate how TypeScript would make the basic project more complex?

Peut etre pour des "juniors" qui viendront ca sera un peu embrouillant

**Comment by gabin-dongmo** [comment]
Oui, c'est sûr que le paradigme est assez différent. Mais une bonne opportunité de se familiariser au typage statique je dirais. C'est en général beaucoup plus fiable, et de ce fait plus utilisé dans des applications d'entreprises...

**Comment by gabin-dongmo** [comment]
Après concertation avec @ln-dev7, il s'avère que c'est trop tôt pour faire un changement aussi profond. C'est donc judicieux de fermer le sujet pour le moment.
Il reste tout de même possible de suivre l'évolution de cette [version alternative](https://github.com/gabin-dongmo/cameroon-portfolios) pour toute personne intéressée.

**Comment by Carter2307** [comment]
D'accord j'ai check ta version en ts c'est vraiment super
